spring:
  application:
    name: jakbu-server
  
  datasource:
    url: jdbc:mysql://localhost:3306/jakbu?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: troy96475
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: 2KxP9sdf8123asdasd98asdyasdasd98y9asd89asdyasd89asd==
  expiration: 86400000 # 24 hours in milliseconds

firebase:
  config-path: firebase-admin.json

server:
  port: 8080

logging:
  level:
    com.jakbu: DEBUG
    org.springframework.security: DEBUG

